### ISSUE TITLE
Add redirect_path to config

### ISSUE THREAD

**Issue by mutablestate** [elixircnx/openmaize#1]
@riverrun To use openmaize in an existing project I needed to override the `add_token/4` redirect as its currently wired to use the `login_dir` configuration setting. 

What do you think about adding a config parameter such as `redirect_path`? The caveat is that any additional roles will probably need custom redirects too.

**Comment by riverrun** [comment]
Will do.

**Comment by riverrun** [comment]
Added redirect_pages map to config. See openmaize-example config/dev.exs file for an example.
One more change: you need to change Openmaize.Authenticate in the web/router.ex file to Openmaize.
