### ISSUE TITLE
Email field instead of name

### ISSUE THREAD

**Issue by Immortalin** [elixircnx/openmaize#10]
Is it possible to use email instead of name?

**Comment by riverrun** [comment]
Hi,

It will be when Elixir 1.2 comes out, which should be very soon. Then you'll be able to configure it.

**Comment by riverrun** [comment]
Added `unique_id` value to the config. Set this to "email" and make sure that your login form returns an email field.
If you have any problems, let me know.

**Comment by riverrun** [comment]
With version 0.12, the way you implement this has changed.
Now there is no configurable value for unique_id. You need to call unique_id when running Openmaize.Login, like this:

```
plug Openmaize.Login, [unique_id: :email] when action in [:login_user]
```

**Comment by Immortalin** [comment]
I see, thank you for implementing this!
