### ISSUE TITLE
add_confirm_token is missing on develop

### ISSUE THREAD

**Issue by mikey0000** [elixircnx/openmaize#101]
DB_Utils.add_confirm_token is missing. But is still present in the templates

**Comment by mikey0000** [comment]
If its meant to be there I am happy to PR it to save you time.

**Comment by riverrun** [comment]
Thanks for raising the issue. I'll deal with it in the next few days.

**Comment by riverrun** [comment]
I think the easiest thing to do is to delete this branch. I've also updated the README to direct Phoenix 1.3 users to the [Phauxth library](https://github.com/riverrun/phauxth).

**Comment by mikey0000** [comment]
Sounds good, thanks!
