### ISSUE TITLE
Authentication email

### ISSUE THREAD

**Issue by Immortalin** [elixircnx/openmaize#11]
It would be great if a confirmation email feature can be added

**Comment by riverrun** [comment]
Could you give me a bit more information, please?
There are two things I want to know:
1. Why is it a good idea?
2. What kind of workflow do you want?
The last point means what do you want Openmaize to do, and what should be the responsibility of your app?

**Comment by Immortalin** [comment]
1. Because you have to confirm whether the email given is a valid email belonging to the user.
2. A config option to be enabled for the registration module.
   This can also be used for passwordless, email-only authentication such as those used by medium.

**Comment by riverrun** [comment]
That should be no problem.
I'll look into it and then get back to you.

**Comment by Immortalin** [comment]
[Here's](https://github.com/bigmachine-io/blackbook/blob/master/lib/blackbook/commands.ex) some code that you might find helpful

**Comment by riverrun** [comment]
Just a progress report.
This is almost finished - I'm just working on the example and fine tuning at the moment.

**Comment by riverrun** [comment]
This is finished now, but it might be a bit different from what you were expecting :)
I've added functions to help with sending a confirmation email, but the actual sending of the email is something that the developer needs to do.
There are two extra functions in Openmaize.Signup:
- gen_token_link - this returns a key (the confirmation token) and a link (to be used as a query string)
- add_confirm_token - this adds the confirmation token to the changeset

There is now a Openmaize.Confirm module, which contains the following function:
- user_email - this checks that the token is correct and still valid and updates the database
  - this takes an optional key_expires_after argument, with which you can define a time limit for the confirmation token

The [Openmaize-phoenix](https://github.com/riverrun/openmaize-phoenix) example app has already been updated with these changes. See the `web/controllers/page_controller.ex` and `web/models/user.ex` files for more info.

**Comment by Immortalin** [comment]
@riverrun thanks!
