### ISSUE TITLE
Add the ability to change field name of scheme

### ISSUE THREAD

**Issue by kzkin** [elixircnx/openmaize#20]
Change "password_hash" field name in scheme through config

**Comment by riverrun** [comment]
Could you tell me why you want this change? It seems to add unnecessary complexity to the Login module.

**Comment by kzkin** [comment]
I want to use database used in rails project (devise scheme). Maybe there's another way ?

**Comment by riverrun** [comment]
What do you want to change it to?

**Comment by mutablestate** [comment]
@riverrun this is probably the devise schema @KozakIvan is using https://github.com/plataformatec/devise/blob/master/test/rails_app/db/schema.rb

**Comment by kzkin** [comment]
Yes, i'm using default devise schema. It is possible to setup password field name through config openmaize, same as in schema. Sorry for my english.

**Comment by riverrun** [comment]
I might add an option to allow you to use "encrypted_password" as well as "password_hash".
It should be ready in 2 or 3 days' time.

**Comment by riverrun** [comment]
In the current master branch, there is now an option to change this in the config.
Just add the following line to your config file (if you're using `encrypted_password` instead of password_hash):

```
hash_name: :encrypted_password
```

Make sure that you remember the `:` before encrypted_password.

**Comment by kzkin** [comment]
Thanks for your attention and time. Works like a charm. Little note that hash_name must equal field name of password in schema (database), maybe specify about that in documentation ? Otherwise, in my opinion, there is a difficult to diagnose error.

**Comment by riverrun** [comment]
You're right. I need to update the documentation.
I'll let you know when I update the hex package.
