### ISSUE TITLE
Mix generators for common features

### ISSUE THREAD

**Issue by Immortalin** [elixircnx/openmaize#22]
It would be great if generators could be added for common features e.g. generate schemas, controllers etc and basic user CRUD. These are stuff that's pretty much needed in any web application and it is much easier to have them generated instead of copying and pasting them from the demo phoenix app.

**Comment by riverrun** [comment]
I agree that this will be a nice feature to have. I'll look into it further.

**Comment by Immortalin** [comment]
@riverrun thank you!

**Comment by riverrun** [comment]
Added basic mix generators to add functions for authorization.
More work will be done on this in the future.
