### ISSUE TITLE
User struct in conn is being set incorrectly

### ISSUE THREAD

**Issue by driventv** [elixircnx/openmaize#27]
When user values are being assigned in the conn, it is being set as a vanilla map instead of a user struct, which will throw errors when invoking certain functions within Phoenix.  For example, if you change a new action to also take the user as an argument, then in your pipeline you use |> build_assoc(:relationship) so that the form and creation are built using the current user id.  Then, call whatever_path(conn, :new) in a template, you will error out because of the build_assoc function is not receiving the correct values in the conn.  `Ecto.build_assoc(%{id: 5, role: "user", username: "john"}, :User_profile, %{})` and it should be `Ecto.build_assoc(%User{id: 5, role: "user", username: "john"}, :User_profile, %{})`  According to Chris Mccord, you can convert it to a %User{} by doing `struct(User, the_map)`  You can see in the stack trace where the error is: https://gist.github.com/iovative/9d374f092faed74a2f9c

**Comment by riverrun** [comment]
Thanks for pointing this out. I'll sort this out later today.

**Comment by driventv** [comment]
Awesome. I hope what I said made sense. It was kind of hard to word it. Thanks!

**Comment by driventv** [comment]
Here are my versions:

`{:phoenix, "~> 1.1.4"},
     {:phoenix_ecto, "~> 2.0"},
     {:postgrex, ">= 0.11.0"},
     {:phoenix_html, "~> 2.3"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.9"},
     {:cowboy, "~> 1.0"},
     {:openmaize, git: "https://github.com/elixircnx/openmaize.git"},
     {:not_qwerty123, "~> 1.0"}]`

 I tested out the new version, and I'm getting a new error further in the process.  Here is the stack trace:

 `Request: GET /dashboard/user_profiles/new
** (exit) an exception was raised:
    ** (UndefinedFunctionError) undefined function Openmaize.UserData.__schema__/2
        (openmaize) Openmaize.UserData.__schema__(:association, :user_profile)
        (ecto) lib/ecto/association.ex:112: Ecto.Association.association_from_model!/2
        (ecto) lib/ecto.ex:468: Ecto.build_assoc/3
        (app) web/controllers/user_profile_controller.ex:24: app.userProfileController.new/3
        (app) web/controllers/user_profile_controller.ex:1: app.userProfileController.action/2
        (app) web/controllers/user_profile_controller.ex:1: app.userProfileController.phoenix_controller_pipeline/2
        (app) lib/phoenix/router.ex:261: app.Router.dispatch/2
        (app) web/router.ex:1: app.Router.do_call/2
        (app) lib/app/endpoint.ex:1: app.Endpoint.phoenix_pipeline/1
        (app) lib/plug/debugger.ex:93: app.Endpoint."call (overridable 3)"/2
        (app) lib/phoenix/endpoint/render_errors.ex:34: app.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4`  

Once build_assoc gets called, here is that function: 

`def build_assoc(%{__struct__: model} = struct, assoc, attributes \\ %{}) do
468    assoc = Ecto.Association.association_from_model!(model, assoc)
469    assoc.__struct__.build(assoc, struct, Dict.delete(attributes, :__meta__))
470  end` 

This is the next step: 

`def association_from_model!(model, assoc) do
112    model.__schema__(:association, assoc) ||
113      raise ArgumentError, "model #{inspect model} does not have association #{inspect assoc}"
114  end`  

That is where the error is encountered.  Please excuse the line numbers inside the functions.  Got to love copy and paste.

**Comment by riverrun** [comment]
Can you give me an example of a struct that does work with your example?

On an unrelated note, I've removed the :not_qwerty123 optional dependency - more details at #26.

**Comment by riverrun** [comment]
Looking at the ecto documentation, it seems that build_assoc needs the first argument to be a struct returned by Repo.get (or a similar function). Maybe if you create a struct by running `user = Repo.get(User, current_user.id)` and send that to build_assoc, you might have more success.

**Comment by driventv** [comment]
That's a good idea. I will give that a shot. If it doesn't cause any conflicts, I would like to keep notqwerty to enforce some basic password rules.

**Comment by riverrun** [comment]
I've just updated master to use the user_model in the :openmaize config (so it creates a struct from your User model combined with the information in the JSON Web Token). I think that will give you what you're looking for.

**Comment by driventv** [comment]
Thanks for the quick turnarounds on this, but that fix didn't work.  Its giving the same error.  Its ok, I will just have to swap out auth frameworks so I can continue on.

**Comment by riverrun** [comment]
I'll look into it further and see what I can come up with.

**Comment by riverrun** [comment]
One option is for you to change data into a struct in the controller file - you can do this for just one function or, by overriding the action function, for all the functions in the module.

I think I'm going to change the current_user data back into a map, as this is probably the most flexible data structure to use, and the developers can convert it if they need to.
