### ISSUE TITLE
Logging out and invalidating tokens

### ISSUE THREAD

**Issue by fadeojo** [elixircnx/openmaize#28]
Is it possible to invalidate tokens when a user logs out?

**Comment by riverrun** [comment]
Work in progress on the develop branch.

**Comment by fadeojo** [comment]
@riverrun saw your changes in the develop brach. Appreciate the great work.

**Comment by riverrun** [comment]
In 0.17, this is the default action.
This is still an experimental feature, and it needs more testing with heavy loads.
