### ISSUE TITLE
Convention over Configuration and Documentation

### ISSUE THREAD

**Issue by claudiojulioferraz** [elixircnx/openmaize#50]
Hello! This seems to be the best authentication system for Elixir. It will be even better when they add support cookies. But it is very costly for those who are starting in the programming world. Some do not want to stop to understand and configure an authentication system, but to focus on building your application. There should be generators that let Openmaize ready for production. Or else a wiki that explains step by step how to set up.

Sorry if this is not the place to discuss this, and thank you for this excellent software.

_Automatically translated._

**Comment by riverrun** [comment]
Thanks for raising this issue.
I hope to be able to spend more time on this in the next few weeks.
I'll let you know when there is any progress on this.

**Comment by riverrun** [comment]
Opened #58.

**Comment by riverrun** [comment]
Much of this has been fixed or it is in progress at the moment.

I'm closing the issue for now. If you have any further issues, please let me know.
