### ISSUE TITLE
Is there an easy way to keep signed in between restarts?

### ISSUE THREAD

**Issue by jejacks0n** [elixircnx/openmaize#51]
I just noticed that with deployment, or a restart, the session is no longer valid. Any insights would be helpful here.

**Comment by riverrun** [comment]
I'm in the middle of making a few changes which will affect this issue. I should have a clearer answer for you in a day or two.

**Comment by riverrun** [comment]
Version 2.0.0, which supports sessions by default, will keep the session alive between restarts.
If you want to use JSON Web Tokens, you will need to switch to using openmaize_jwt version 1.0 (which is going to be released soon).
