### ISSUE TITLE
Persist session to avoid logouts on VM restart

### ISSUE THREAD

**Issue by noma4i** [elixircnx/openmaize#52]
Is it possible? In dev it's a pain when every app restart it leads to user logout. For production all users are kicked on app/vm restart

**Comment by jaimeiniesta** [comment]
Looks like a duplicate of https://github.com/riverrun/openmaize/issues/51

**Comment by riverrun** [comment]
If you're happy using cookie-based sessions, instead of JSON Web Tokens, then this issue will be solved in version 1.1, which I should be releasing in a day or two (you can see the progress on the `sessions` branch).
I'll close this issue now, and I'll make any updates to #51.

**Comment by noma4i** [comment]
JWT suites well on stateless apps other then you use phoenix and state is persistent.
