### ISSUE TITLE
Rename find_user_byid

### ISSUE THREAD

**Issue by zimt28** [elixircnx/openmaize#54]
Why is [this](https://github.com/riverrun/openmaize/blob/master/lib/openmaize/database.ex#L37-L44) called `find_user_byid`? IMO it would be nicer if it was called `find_user_by_id`. It might be changed in `1.1`.

**Comment by riverrun** [comment]
I'll think about it and let you know.

**Comment by riverrun** [comment]
Renamed in 2.0.0.
