### ISSUE TITLE
Auth from code not via form submission

### ISSUE THREAD

**Issue by noma4i** [elixircnx/openmaize#57]
Any ability to login as any user right from controller?

**Comment by noma4i** [comment]
Real world example:  I need to auth as other users to get same experience.

**Comment by riverrun** [comment]
I'm not sure that I know what you mean. Do you want to be authenticated as any user without logging in? And is this in development or production?

**Comment by noma4i** [comment]
It's usual behaviour in web apps when you been admin auth as someone else or make immediate auth of just signed up user. Generally used in controller like: `Openmaze.authenticate(conn, user)` where user is record from db.

Right now set_session is a part of Plug based module and I can't invoke it in a way described above.

**Comment by riverrun** [comment]
For the immediate auth of just signed up user, you should be able to add a call to `put_session(conn, :user_id, user_id)` to the signup logic (if there are no errors, or course).
As for viewing a resource as if you are another user, it depends a lot on the nature of your app. To be able to help you, I need the answer to the following questions:
1. How are you authorizing user resources - using roles, id, something else?
2. Do you always want to access certain pages as a certain user?
3. How do you want to access a page as another user - are you going to use an admin control panel or some other way?

**Comment by noma4i** [comment]
put_session works fine for just signed up user. All other stuff is more about my crazy app ;) Thanx a lot!
