### ISSUE TITLE
Confirm link can be requested multiple times

### ISSUE THREAD

**Issue by paulgoetze** [elixircnx/openmaize#62]
I’m using the "confirmation email after signup" functionality similar to the one in the [openmaize-phoenix](https://github.com/riverrun/openmaize-phoenix-example) example app with using the ConfirmEmail plug in my controller.

``` elixir
plug Openmaize.ConfirmEmail, [key_expires_after: 30] when action in [:confirm]
```

It looks like the confirmation link can be requested multiple times and always updates the user’s `confirmed_at` timestamp. 

Is this expected behaviour, or should there be a check and an error message (sth. like "Your account is already confirmed") once the email was confirmed? Or is this something I would have to care about explicitly? If, what would be a good approach to do this check?

**Comment by riverrun** [comment]
Yes, you're right. It should result in an error if the user is already confirmed.

**Comment by paulgoetze** [comment]
Thanks @riverrun, that was fast!
