### ISSUE TITLE
Generator lacks some of the fields used by otp and user role admin

### ISSUE THREAD

**Issue by guidotripaldi** [elixircnx/openmaize#75]
Hi David,
I've noticed that the `priv/templates/phoenixauth/user_migration.exs` used by the generator, lacks some of the fields (`:otp_required`, `:otp_secret`, `:role` and `:remember`) used by the "advanced" openmaize version.
It is just an oversight or an intended behavior? Are we supposed to add them by hand to the project, or we may safely enhance the generator so to speedup the project setup?

**Comment by riverrun** [comment]
At the moment, this is intended. The generator provides the most basic setup.
We can of course work on improving this. It depends a lot on what people want.

**Comment by riverrun** [comment]
I think things like :otp_required and :role can be addressed in the wiki -- maybe have a brief explanation together with some snippets of code that people could copy and paste.
