### ISSUE TITLE
How to use Phoenix.Token?

### ISSUE THREAD

**Issue by puruzio** [elixircnx/openmaize#77]
I'm trying to get Openmaize to work with Phoenix.Token for user authentication. I tried to modify `authenticate.ex` in the library like this, but it doesn't seem to be called as I was expecting it.

Can you please tell me what is the right way to use Phoenix.Token with Openmaize?
 
 ```
 defp set_current_user(user, conn) do 
    token = Phoenix.Token.sign(conn, "user socket", user.id)
    IO.inspect(token)
    conn
    |> assign(:current_user, user)
    |> assign(:user_token, token)
```

**Comment by riverrun** [comment]
Could you let me know the output of `IO.inspect(token)`?

If it's nil or there's an error, let me know the output to `IO.inspect(user)` (just above the `token =` line).

If `IO.inspect(token)` returns a string, let me know the output of `assign(:user_token, token) |> IO.inspect`.

**Comment by puruzio** [comment]
Actually it doesn't seem to hit `set_current_user` line at all. Is there anything that needs to be wired up other than adding the plug `Openmaize.Authenticate` in the router.ex?

I did follow the steps indicated at https://github.com/riverrun/openmaize for installation and setup.

**Comment by puruzio** [comment]
Adding the following to router.ex did the trick. Thanks.
```
  pipeline :browser do
   ...
    plug Openmaize.Authenticate
    plug :put_user_token
  end
  
  defp put_user_token(conn, _) do
    if current_user = conn.assigns[:current_user] do
      token = Phoenix.Token.sign(conn, "user socket", current_user.id)
      assign(conn, :user_token, token)
    else
      conn
    end
  end
```

**Comment by riverrun** [comment]
Glad to hear you got it working.
