### ISSUE TITLE
Installer cannot find templates

### ISSUE THREAD

**Issue by ghost** [elixircnx/openmaize#82]
I'm having an issue when trying to execute mix openmaize.phx.

It fails with 
```
** (File.Error) could not read file "/data/develop/elixir/security/openmaize/installer/phoenix/templates/phx_api/session_controller.ex": no such file or directory
```

Maybe some constant slipped thru?

**Comment by markman123** [comment]
I got around this by compiling my own version from the repo and installing from there

**Comment by riverrun** [comment]
Thanks for letting me know.

**Comment by riverrun** [comment]
I've updated the archive with a fix. If you could try it out on your machine, that would be great.

**Comment by ghost** [comment]
Thanks! It worked!
