### ISSUE TITLE
Installer Generates API template for HTML site.

### ISSUE THREAD

**Issue by ghost** [elixircnx/openmaize#85]
When using the installer for an html site, and using the --confirm option, the controller for password resets appears to be the one used for APIs.

The issue seems to be [here](https://github.com/riverrun/openmaize/blob/master/installer/phoenix/lib/openmaize_phx.ex#L83).

**Comment by riverrun** [comment]
Thanks for pointing this out. I've updated the archive, so it should be ok now.

If you are using the `unique_id` argument (to use email instead of username, for example), you will need to edit the `session/new.html.eex` file. I'm thinking of dropping this argument - see #86 for details.

**Comment by ghost** [comment]
Thanks! I'll bew playing around during the weekend, and ty things out :smile:
