### ISSUE TITLE
Provide two-factor authentication workflow guide 

### ISSUE THREAD

**Issue by riverrun** [elixircnx/openmaize#93]
There is an Openmaize.OnetimePass plug which provides a one-time password check. However, there is currently no guidance on how to integrate this into a web application. Considering that many security issues arise from implementation errors, there needs to be more information about implementation in the wiki and / or documentation.

**Comment by julienmarie** [comment]
+1 on this one

**Comment by riverrun** [comment]
Moved to [this issue](https://github.com/riverrun/phauxth/issues/2)
