### ISSUE TITLE
Move repo and user_model values to the config

### ISSUE THREAD

**Issue by riverrun** [elixircnx/openmaize#95]
At the moment, the values for repo and user_model are worked out by the Openmaize.Utils module, and they are evaluated to be MyApp.Repo and MyApp.User. With Phoenix 1.3, MyApp.User should be MyApp.Accounts.User, but this is Phoenix-specific, and one of the goals of Openmaize is that it is not tied down to any particular framework.

The current plan is to add these values to the config. The branches `phx_1.3` and `develop` show examples of this, the difference between them being that `phx_1.3` allows these values to be overridden, whereas in the `develop` branch, the values are fixed.

My preference is for the version in the `develop` branch. However, if someone can provide a strong argument for allowing these values to be overridden, I will accept that.

**Comment by fabrik42** [comment]
Hi! Thanks for looking into that, but  I can't find a `phx_1.3` branch in this repo, there seems to be only master and develop.

**Comment by wulymammoth** [comment]
@fabrik42 I think it's been removed. It was here a couple of days ago. I was just looking for it as well. 

@riverrun was it removed because you'll no longer provide a Phoenix-specific generator per your comment above??

**Comment by riverrun** [comment]
The changes are now on the develop branch.
