### ISSUE TITLE
Spring cleaning / reorganization -- discussion

### ISSUE THREAD

**Issue by riverrun** [elixircnx/openmaize#99]
I'm experimenting with the idea of having a quite small base library and moving the confirmation functions into a separate library.

## Reasons

* not everyone will want to use the confirmation functions, and so it is not necessary to have them in the main package
* it is organizationally clearer what each part is meant to do
* some of the changes might make it easier to customize the core package

## Progress

[Here](https://github.com/riverrun/opnmz) is the work I've done so far on the base / core library. I'm going to add a opnmz_confirm repository in a day or two.

Any feedback I can get will be most welcome.

**Comment by fabrik42** [comment]
Hi! 

In general, I would be fine with this as long as there is a specified upgrade path. :)
Maybe this provides an opportunity to add more complex confirmation scenarios?

Keep up the good work!

**Comment by riverrun** [comment]
At the moment, I just want to try a few ideas, and I will try to make the upgrade path as painless as possible.

I think it would be nice to keep the core fairly lightweight and concentrate on making the modules easy to customize. That way, we can help developers tailor the Plugs / authentication modules to their specific needs.

About confirmation, it would be nice to have something in place for phone confirmation, which I imagine will only get more popular, but I haven't really got anywhere with that yet.

[Here](https://github.com/riverrun/phauxth)'s another simplified version, but this one also depends on Phoenix, so that I can take advantage of Phoenix Token (and possibly other Phoenix goodies in the future).

**Comment by riverrun** [comment]
[Here is the core app](https://github.com/riverrun/phauxth) and
[here is the confirmation app](https://github.com/riverrun/phauxth_confirm).

The tentative plan at the moment is to move development to these apps when Phoenix reaches 1.3. The installer for Openmaize will be kept at the pre-1.3 stage, and Openmaize will be maintained on a 'bug-fix only' basis.

The main differences between Openmaize and the Phauxth apps are:

* Phauxth depends on Phoenix
* Phauxth is designed to be more extensible
* Phauxth is more modular

I will keep you posted about any other developments.

**Comment by fabrik42** [comment]
This sounds good to me. Just my two cents, but I think it's a good idea to keep Phoenix as a dependency and use existing solutions (like Plug.Session, Phoenix.Token) instead of reinventing the wheel.

Also, I like the idea of making Phoenix 1.3 the breaking point, this way I can plan my upgrade better.

**Comment by riverrun** [comment]
[Phauxth app](https://github.com/riverrun/phauxth)

[Hex package](https://hex.pm/packages/phauxth)

[Phauxth installer for Phoenix 1.3](https://github.com/riverrun/phauxth/raw/master/installer/archives/phauxth_new.ez)

I've put the confirmation functionality back into the main library. I've also tried to make it easier to handle user confirmation with methods other than email -- phone, for example.

I will add an upgrade guide sometime this week.
